package com.ufufund.ufb.model.enums;


public enum ErrorInfo {
    
	NECESSARY_EMPTY("NECESSARY_EMPTY"),
	NOT_EQUALS_PASSWORD("NOT_EQUALS_PASSWORD"),
	NOT_EQUALS_BANKACCO("NOT_EQUALS_BANKACCO"),
	FIELD_FORMAT_WRONG("FIELD_FORMAT_WRONG"),
	ALREADY_REGISTER("ALREADY_REGISTER"),
	ALREADY_BIND("ALREADY_BIND"),
	WRONG_LOGIN_CODE("WRONG_LOGIN_CODE"),
	WRONG_TRADE_PASSWORD("WRONG_TRADE_PASSWORD"), // 不正确
	CANNOTEQUALPWD("CANNOTEQUALPWD"), // 不能与登录密码相同
	CANNOTEQUALTRADEPWD("CANNOTEQUALTRADEPWD"), // 不能与交易密码相同
	NO_IDCARDNO("NO_IDCARDNO"),
	FREEZE_USER("FREEZE_USER"),
	WRONG_LOGIN_PASSWORD("WRONG_LOGIN_PASSWORD"),
	//WRONG_LOGIN_IDCARDNO("WRONG_LOGIN_IDCARDNO"),
	BANK_VERI_FAIL("BANK_VERI_FAIL"),
	
	
	AUTO_STATE_ERROR("0511"),
	AUTO_NEXTDAY_ISWORKDAY("0512"),
	
	ORG_MUST_SAVE_GRADE("7001"),
	ORG_TERM_IS_CLOSE("7002"),
	
	ORG_NO_STUDENTS("7003"),
	ORG_NO_CHARGE("7004"),
	ORG_DATE_WRONG("7005"),
	
	
	SYSTEM_ERROR("SYSTEM_ERROR")
	;
	
	
	
	//WRONG_PASSWORD("WRONG_IDCARDNO"),
	//WRONG_MOBILE("WRONG_MOBILE");
	//个人
	//ORGANIZATION(2);//机构
	
	private String errorCode;

	private ErrorInfo(String errorCode) {
		this.errorCode = errorCode;
	}

	public String value() {
		return errorCode;
	}

}